### ISSUE TITLE
Can not add members to playbook

### ISSUE THREAD

**Issue by risingwolf21** [mattermost/mattermost-plugin-playbooks#1040]
When I try to edit my playbook and add members via the playbook access and memebers there, or use the Actions to invite memebers, i get an error. From the chrome developer tools i get this:

`TypeError: Cannot read properties of undefined (reading 'filter')
    at ND (invite_users_selector.tsx:63:44)
    at Xr (react-dom.production.min.js:153:146)
    at Pi (react-dom.production.min.js:175:309)
    at bs (react-dom.production.min.js:263:406)
    at mu (react-dom.production.min.js:246:265)
    at du (react-dom.production.min.js:246:194)
    at ou (react-dom.production.min.js:239:172)
    at react-dom.production.min.js:123:115
    at t.unstable_runWithPriority (scheduler.production.min.js:19:467)
    at Yn (react-dom.production.min.js:122:325)`

Some other error wich might be relevant: 

`assign_owner_selector.tsx:47 Error searching user profiles in custom attribute settings dropdown.`

Also in Mattermost the playbooks are getting a white screen and can not be edited.

The request for the users also fails with an `ERR_CONNECTION_CLOSED`:

`https://****/api/v4/users?active=true&in_team=swuryznripbkxp6tnw1h8cug5a&page=0&per_page=200&sort=`

I am using mattermost in a docker container with Mattermost Version 6.3.0
And the current playbooks version with 1.23.0

If you need more detailed information hit me up.
Thanks :)

**Comment by lieut-data** [comment]
Thank you for this report! @calebroseland, could you take a stab at reproducing this and follow up with @risingwolf21 for any extra details needed?

**Comment by risingwolf21** [comment]
The error was that I set the Site Url wrong in the .env file. By default it is using $DOMAIN wich is not correct for starting it with a docker container by me. I corrected it to http://localhost:9201 and now it is working properly.
