### ISSUE TITLE
Running Mattermost 6.4.1, I see Unable to activate plugin (playbooks)

### ISSUE THREAD

**Issue by joho1968** [mattermost/mattermost-plugin-playbooks#1077]
(As requested, I'm "re-opening" this here instead.)

#### Summary
After upgrading from MM 6.3.x to .6.4.1, I see this in the log: "Unable to activate plugin","caller":"app/plugin.go:142","plugin_id":"playbooks"

#### Steps to reproduce
I don't know, I get it every time I re-start MM

#### Expected behavior
I would expect any migration to successfully complete.

#### Observed behavior (that appears unintentional) 
```
{"timestamp":"2022-03-07 19:55:58.715 Z","level":"error","msg":"Unable to activate plugin","caller":"app/plugin.go:142","plugin_id":"playbooks","error":"failed to run migrations: failed to complete migrations: error executing migration from version 0.25.0 to version 0.26.0: failed adding column CategoryName to table IR_Playbook: Error 1118: Row size too large. The maximum row size for the used table type, not counting BLOBs, is 8126. This includes storage overhead, check the manual. You have to change some columns to TEXT or BLOBs"}
{"timestamp":"2022-03-07 19:56:03.920 Z","level":"warn","msg":"Unrecognized config permissions tag value.","caller":"api4/config.go:379","tag_value":"sysconsole_write_*_read"}
```

#### Other information
- Ubuntu 20.04.LTS
- MariaDB 10.6
- MM 6.4.1 (upgraded from MM 6.3.x)

**Comment by lieut-data** [comment]
Hi @joho1968! Thanks for opening this ticket here -- ironically, we have an open ticket with a very similar description back in the server repository where you first filed a report: https://github.com/mattermost/mattermost-server/issues/19572.

I'm curious if some of the feedback @crspeller provided there might be useful to you here?

I'll also note that we don't /officially/ support MariaDB, though we have made an effort locally to run our CI against it to avoid any obvious breakage. If you can help us figure out how to harden our migrations to avoid this, we'd be happy to help incorporate a fix!

**Comment by joho1968** [comment]
Thanks for getting back to me. I do realize MariaDB and MySQL are (no longer) identical, but I seriously think you should make sure that MM works properly with MariaDB as good as it does with MySQL. We've been running MariaDB from the start (and do on most of our hosting instances, both internal and for clients).

I did read those threads, and I have attempted to modify the innodb_log_file_size setting, but the error message still appears when I re-start MM.

I'm guessing the "solution" is in the error message: **You have to change some columns to TEXT or BLOBs**

_("the innodb_log_file_size setting should be 10 times larger than the largest BLOB data size found in the rows of your tables plus the length of other variable length fields (VARCHAR, VARBINARY, and TEXT type fields)")_

The problem is that I wouldn't want to directly modify the database without being given pointers as to which columns I should change, and those pointers probably should come from the Mattermost team :blush: 

Seeing as how we went from 6.3.x to 6.4.x, perhaps that could help your team track down changes made in the database structure, which in turn are causing these "migration issues" ... ?

**Comment by lieut-data** [comment]
Thanks for the detailed notes, @joho1968! What's especially curious is that this migration has been part of the playbooks product since we shipped in v6.0, and isn't newly introduced in v6.4.x.

Is there a chance you only recently enabled Playbooks? Were there any other changes made in tandem to upgrading to this release?

**Comment by joho1968** [comment]
Hmm ... that's interesting @lieut-data, I didn't know that. I must not have paid attention to this issue in the logs after a previous upgrade then, as it's likely it was there before. We haven't enabled/disabled anything for some time, so I don't think it's that.

No other changes have been made; I normally go into the System Console and change an "innocent value" from, say, 2 to 3, save, and then back to 2 again; in case some configuration needs to be migrated. But no other changes.

I haven't spent any serious time looking into the database structures, but is it possible that the error message is "correct" in that some boundaries and/or size limits are exceeded for InnoDB?

**Comment by lieut-data** [comment]
Thanks again for the extra context @joho1968. To date, we haven't encountered this issue with MySQL nor a freshly installed MariaDB, so I'm inclined to think we have two paths forward:
* Find some default (perhaps legacy) configuration that can be changed
* Revisit our approach to this table's schema.

As my team investigates the latter, I wonder if you might be able to help us with the former? I know you tried changing `innodb_log_file_size` without success. I wonder if you can reproduce this problem with a fresh MariaDB installation? If not, I wonder if a diff between the two instance configurations might help shed light on what configuration values we could tweak?

**Comment by joho1968** [comment]
I don't think I can "try this" with a "fresh MariaDB" installation, seeing as how other things are running on that host too. But we could certainly compare notes on the MariaDB version and configuration.

**Comment by lieut-data** [comment]
Hi @joho1968! I'm going to close out this old issue for now, but if you find something we can share with those users that prefer MariaDB, I'd be happy to help update documentation.
