### ISSUE TITLE
No notification if trying to save private playbooks on MM Team Edition

### ISSUE THREAD

**Issue by bujinin** [mattermost/mattermost-plugin-playbooks#1080]
Hi,
I just started to play around with playbooks when I noticed a quite confusing thing. When I create a private playbook on a MM Team Edition server and try to save it, nothing is happening. I was lucky because I could see the following in the server logs:
`{"timestamp":"2022-03-11 09:50:32.562 +01:00","level":"warn","msg":"public error message: Not authorized; internal details: private playbooks are not available with your current subscription: not covered by current server license","caller":"app/plugin_api.go:931","plugin_id":"playbooks"}` 
but for all the other users, that might be quite a negative user experience.

Maybe you could show a popup, that private playbooks are not available for MM Team Edition, right when you try to create them or even "disable" them completely, if the right license is not available.

**Comment by Phrynobatrachus** [comment]
Hello! This was fixed in `1.24.1` up, the UI should look like this:

![Screenshot from 2022-03-11 09-53-20](https://user-images.githubusercontent.com/3723666/157891625-2c663efd-0e5a-4b63-b341-89fc0ebbc895.png)

Can you check which version you're running (found in `System Console > Plugins`) please? If you're on `1.24.1` or `1.25.0` and still having this issue I'll make sure to bring it up with the team. 

Thanks for the report!

**Comment by bujinin** [comment]
Thanks for the quick response! You are right, we are currently on 1.23.0. However, I don't see any way to update it. Is there a way to do it manually or do I have to wait, until its shown in the marketplace? Btw, we are using the current ESR version of MM.

**Comment by Phrynobatrachus** [comment]
There's a few options for updating, here are some I typically use:

1) if you use `mmctl` and have already authenticated with your server, you should be to simply run
 
`mmctl plugin install-url --force https://github.com/mattermost/mattermost-plugin-playbooks/releases/download/v1.25.0/playbooks-1.25.0.tar.gz`

2) via [manual upload](https://developers.mattermost.com/integrate/admin-guide/admin-plugins-beta/?&redirect_source=about-mm-com#custom-plugins)

3) If a newer version is available in the marketplace, there should be an upgrade link in the same System Console plugin section. 

I might be overlooking some interaction with Team Edition or ESR that means 3 isn't an option in this case, but 1 or 2 should definitely work for you. Let me know if you have trouble though.

**Comment by lieut-data** [comment]
@bujinin, right now we're primarily focussing on shipping Playbooks as a pre-packaged plugin, with the intention to upgrade it alongside your regular Mattermost upgrade process. As a result, it isn't listed in the marketplace.

In the future, the product won't be implemented as a plugin, but will be shipped in the core by default.

**Comment by Phrynobatrachus** [comment]
I'm going to close this issue for now, but please feel free to re-open if you need any more help.
