### ISSUE TITLE
 Saving playbook with semicolon in task description fails

### ISSUE THREAD

**Issue by reftel** [mattermost/mattermost-plugin-playbooks#1175]
# Summary

Pressing the "Save" button on a playbook having a task with a description that contains a semicolon does nothing, both in Desktop on Mac and Webapp with Firefox.
# Steps to reproduce

Create a playbook. Add a task. Write a description that contains a semicolon. Press the Save button.
# Expected behavior

The playbook is saved, and the starting page of the playbook (the one with Preview and Usage tabs) is shown.
# Observed behavior (that appears unintentional)

Nothing happens. No error messages, nothing. When using the Webapp with Firefox, the following is logged to the Developer Tools console (domain name and playbook ID altered) when updating an existing playbook ot include a semicolon in a task description:
```
XHR PUT https://chat.example.com/plugins/playbooks/api/v0/playbooks/ds8324jr4w90fesjf4we0greno
[HTTP/1.1 403 Forbidden 21ms]

Uncaught (in promise) Error: 
    Q Redux
    Sf client.ts:671
    df client.ts:227
    onClick playbook_edit.tsx:345
    s Transition.js:264
    m Transition.js:274
    p Transition.js:293
    p Transition.js:297
    React 5
    U Transition.js:401
    React 2
    unstable_runWithPriority scheduler.production.min.js:12
    React 3
client4.ts:3834:8
    onClick playbook_edit.tsx:347
    AsyncFunctionThrow self-hosted:642
    (Async: async)
    s Transition.js:264
    m Transition.js:274
    p Transition.js:293
    p Transition.js:297
    React 5
    U Transition.js:401
    React 2
    bind_applyFunctionN self-hosted:1319
    Xt self-hosted:1282
    unstable_runWithPriority scheduler.production.min.js:12
    React 3
    bind_applyFunctionN self-hosted:1319
    Vt self-hosted:1282
```
and the following when creating a new playbook with a task description containing a semicolon:
```
XHRPOSThttps://chat.example.com/plugins/playbooks/api/v0/playbooks
[HTTP/1.1 403 Forbidden 17ms]

Uncaught (in promise) Error: <html><head><title>Request Rejected</title></head><body>The requested URL was rejected. Please consult with your administrator.<br><br>Your support ID is: 14456753557782223731<br><br><a href='javascript:history.back();'>[Go Back]</a></body></html>
    Q Redux
    wf client.ts:635
    Cf client.ts:582
    df client.ts:223
    onClick playbook_edit.tsx:345
    s Transition.js:264
    m Transition.js:274
    p Transition.js:293
    p Transition.js:297
    React 5
    U Transition.js:401
    React 2
    unstable_runWithPriority scheduler.production.min.js:12
    React 3
client4.ts:3834:8
```
# Possible fixes

Unknown.

# Version information
We´re running:
```
Mattermost Enterprise Edition
Modern communication from behind your firewall.

Mattermost Version: 6.3.6
Database Schema Version: 6.3.6
Database: postgres
```
The Mattermost Desktop version I´m using is 5.0.4.17220. I don´t know which version of the Playbook plugin we use.

**Comment by lieut-data** [comment]
Hi @reftel! This is very unexpected. Are there any other steps to reproduce? Trying locally, I'm able to create a new playbook with a description having a semicolon:

<img width="393" alt="CleanShot 2022-05-10 at 11 30 55@2x" src="https://user-images.githubusercontent.com/1023171/167653483-2f6bd137-6242-484b-a105-b91af74b878e.png">

Does it reproduce with any other types of changes? Also, do you have access to the server logs in question for when this fails?

**Comment by reftel** [comment]
I think this may be related to an overly-eager WAF we have. The 403 response is:

```
HTTP/1.1 403 Forbidden
Cache-Control: no-cache
X-Cnection: close
Content-Type: text/html; charset=utf-8
Pragma: no-cache
Content-Length: 247

<html><head><title>Request Rejected</title></head><body>The requested URL was rejected. Please consult with your administrator.<br><br>Your support ID is: 15535947284402906985<br><br><a href='javascript:history.back();'>[Go Back]</a></body></html>
```

which I do not believe is from neither Mattermost nor Playbook. Still, some kind of error message when saving fails would have been nice - I lost quite a bit of work when I had finished defining a playbook, only to have save fail without explanation.

**Comment by reftel** [comment]
It seems that in this case, the WAF behaviour is related to the request being sent with `Content-Type: text/plain;charset=UTF-8`, but with a json body. Is this intentional?

**Comment by lieut-data** [comment]
@reftel, I'm really sorry that this bug caused you to lose data. We absolutely should be handling this error case better.

When I test locally, I do see requests being made using the correct `Content-type: application/json` header:

![CleanShot 2022-05-11 at 13 35 41@2x](https://user-images.githubusercontent.com/1023171/167902253-e2c67ea6-5af3-4fa1-b597-12bc9c3f0456.png)

**Comment by reftel** [comment]
Thanks for investigating this! I´m attaching a HAR recording with sensitive values redaced:
[playbook_with_semicolon.zip](https://github.com/mattermost/mattermost-plugin-playbooks/files/8672409/playbook_with_semicolon.zip)
Could it be that we have different versions of the Playbook plugin? How do I check which version we use?

**Comment by lieut-data** [comment]
Thanks for the HAR, @reftel! I missed that you were using Firefox in your original post, and so tried to reproduce there for good measure, but still found `application/json` correctly emitted as the `Content-Type`. And perusing the code, I can't find a path that would ever send `text/plain` (nor append a `charset`). 

Do other POST requests to Mattermost also show `text/plain`, e.g. authoring a new post? (They should all be `application/json`.)

You can validate the Playbooks version from the system console of your server:

![CleanShot 2022-05-11 at 15 58 40@2x](https://user-images.githubusercontent.com/1023171/167925632-24259cab-39af-42da-b6eb-86ae6a1f1a08.png)

**Comment by reftel** [comment]
No, other requests use application/json. I´m attaching a HAR captured when sending the message "test" to myself:
[mattermost-chat.zip](https://github.com/mattermost/mattermost-plugin-playbooks/files/8675719/mattermost-chat.zip)
. I don´t have access to the system console, but I´ll try to get hold of someone who has.

**Comment by reftel** [comment]
We´re running version 1.23.0 of the Playbook plugin.

**Comment by lieut-data** [comment]
@reftel, I wonder if you'd be willing to try reproducing on a cloud test server I just setup? Running 6.3.6 and Playbooks v1.23.0:
<img width="623" alt="CleanShot 2022-05-12 at 14 49 01@2x" src="https://user-images.githubusercontent.com/1023171/168137535-29da6447-7747-49e8-8afe-d43f8cd50b7d.png">
<img width="691" alt="CleanShot 2022-05-12 at 14 49 17@2x" src="https://user-images.githubusercontent.com/1023171/168137539-24e6543e-ebc4-4acb-a743-b011448f876e.png">


You can access at: https://issues-1175.test.mattermost.cloud and login with:

| Username | Password |
| -- | -- |
| sysadmin | Sys@dmin123 |

**Comment by lieut-data** [comment]
Good news! This was previously identified and fixed as part of https://mattermost.atlassian.net/browse/MM-40751.

Bad news: Playbooks was importing an older version of the webapp client, and didn't get this fix until v1.24, which shipped with 6.4 (February 2022).

@reftel, do you have the option of upgrading your server? Or are you sticking to our 6-month ESR cadence?

**Comment by reftel** [comment]
We stick to ESRs, so I guess we will have to wait until July to verify the fix.

**Comment by lieut-data** [comment]
@reftel, I can't necessarily promise an ESR update for v6.3, but do you regularly update when we ship patches? @amyblais, do you know if we have any updates to v6.3 planned in the near future into which we might consider a patch for Playbooks to better support WAF like the webapp does?

**Comment by amyblais** [comment]
@lieut-data There are a few bug fix candidates queued for a v6.3 dot release in the near future (no planned release date yet), so feel free to cherry-pick the fix and it will get included in the next dot release. Let me know when it's done.

**Comment by lieut-data** [comment]
cc @Phrynobatrachus, heads up that we may consider a `v1.23.2` that bumps our webapp dependencies.

**Comment by reftel** [comment]
Yes, we do install patches, so an ESR update would be welcome, though I´d understand if you would rather avoid adding changes to an ESR update.

**Comment by lieut-data** [comment]
Thanks, @reftel! I'm reviewing a fix as part of https://github.com/mattermost/mattermost-plugin-playbooks/pull/1188 and hope to include it in the next patch release for the ESR.

**Comment by lieut-data** [comment]
@reftel, just a heads up that a fix for this should ship in the next ESR. Dates TBD.

**Comment by reftel** [comment]
Thank you!

**Comment by reftel** [comment]
We have now installed version 6.3.9, and saving playbooks with semicolons in descriptions now works. Thank you!

**Comment by lieut-data** [comment]
Sweet, thank you for confirming @reftel!
