### ISSUE TITLE
Unable to Install Playbooks-Plugin

### ISSUE THREAD

**Issue by excedra** [mattermost/mattermost-plugin-playbooks#1213]
Hello,

when trying to install the Playbooks-Plugin from the Marketplace on Mattermost 6.7.0, I get the following error:

_{"timestamp":"2022-05-25 16:55:37.128 +02:00","level":"error","msg":"Could not find the requested marketplace plugin.","caller":"web/context.go:105","path":"/api/v4/plugins/marketplace","request_id":"XXX","ip_addr":"XXX","user_id":"XXX","method":"POST","err_where":"GetMarketplacePlugin","http_code":500,"err_details":"plugin not found"}_

How can this be fixed?

**Comment by lieut-data** [comment]
cc @hanzei, re: https://community.mattermost.com/core/channels/integrations/8noz8k9ktpbpfdyhnfmby7xr4e

**Comment by slate17** [comment]
> Hi @excedra & @slate17! We are aware of an issue installing plugins from the pre-packaged cache (when they aren't actually in the marketplace, but just appear there because they are pre-packaged).
> 
> In general, these plugins should be automatically installed and enabled, unless your server is configured not to automatically install pre-packaged plugins. Can you check if `Enable Automatic Prepackaged Plugins` is turned on in your plugin settings for the Mattermost server?
> 
> Longer term, this product will stop shipping as a plugin and be compiled directly into the server, making most of this moot. If the pre-packaging isn't working for you, you can still download and manually install the plugin from https://github.com/mattermost/mattermost-plugin-playbooks (this repository).

`Enable Automatic Prepackaged Plugins` is enabled. 

At first the update from 1.23 to 1.27 through the marketplace Interface was failing and when I tried removing the plugin and installing again, that failed as well.

I could manually install via Upload though.

**Comment by lieut-data** [comment]
Sorry for the long delay in responding, @slate17! Did you ever sort out this issue? I might also suggest upgrading the Mattermost Server to the latest v7.4 to see if the issue resolves.
