### ISSUE TITLE
Unwanted port exposure

### ISSUE THREAD

**Issue by wfjsw** [mattermost/mattermost-plugin-playbooks#1359]
The playbook plugin is serving Prometheus info at port `9093` on all interfaces without config items to control its behavior.

**Comment by lieut-data** [comment]
Thank you for the report, @wfjsw! We'll triage this today.

**Comment by lieut-data** [comment]
@wfjsw, a number of our plugin-based products have exposed discrete metric ports, so we'd like to take the opportunity to clean things up and expose all metrics through the main server port instead.

But in advance of this overhaul, I'm looking into a PR to at least have Playbooks honour the existing `MetricsSettings.Enable` flag in the server. Does that suit your use case: disabling metrics altogether for this instance?

**Comment by wfjsw** [comment]
Sure that's enough for me.

**Comment by lieut-data** [comment]
Excellent! This change should land in our upcoming v7.2 (August 15th).
