### ISSUE TITLE
GraphQL API for participating in a run

### ISSUE THREAD

**Issue by crspeller** [mattermost/mattermost-plugin-playbooks#1402]
Add graphql APIs for participating and removing participation in a run:

```graphql
type Mutation {
    ...
    addRunParticipant(runID: String!, userID: [String!]!): String!
    removeRunParticipant(runID: String!, userID: String!): String!
}
```
Follow existing pattern for add and remove playbook member. 
Add and remove participation should follow the permissions for viewing a run. Note that this means participation means nothing in terms of permissions. It's only a virtual barrier to access. 

- [x] create graphql mutations with current leave/participate behavior (still channel members) https://github.com/mattermost/mattermost-plugin-playbooks/pull/1422
- [x] store and service functions to handle add/remove members
- [x] connect graphql to new service functions 
- [x] clean channel checks when joining
- [x] e2e tests for run gql query and mutations
- [ ] permissions change not covered in this task. RunView and RunManageProperties still rely on channel membrs

**Comment by trilopin** [comment]
@crspeller I changed the addRunParticipant to support multiple users in one shot.

**Comment by crspeller** [comment]
@trilopin Should it be symmetric then with removeRunParticipant also taking multiple users?

**Comment by trilopin** [comment]
> @trilopin Should it be symmetric then with removeRunParticipant also taking multiple users?

UI interaction does not justify it, but we can create a mutation that accepts multiple removals too if you see value in the symmetry.
