### ISSUE TITLE
Modify existing participation flows

### ISSUE THREAD

**Issue by crspeller** [mattermost/mattermost-plugin-playbooks#1416]
Participation currently means joining the linked channel. Places where users participate need to be modified so they participate rather than join the channel.

Known locations (search for more): 
- [x] Run detail page participate button [Figma Designs](https://www.figma.com/file/oBERv3BlbjpcFMKgPAo7E5/%F0%9F%91%A5-Members-%E2%89%A0-Participants?node-id=92%3A118276)
- [ ] Playbook action to "invite members" to the channel should instead "invite participants"

**Comment by trilopin** [comment]
Participate button has been already migrated as part of https://github.com/mattermost/mattermost-plugin-playbooks/issues/1402
