### ISSUE TITLE
Add RHS screen for channel has a run but you can't access it

### ISSUE THREAD

**Issue by crspeller** [mattermost/mattermost-plugin-playbooks#1441]
If the playbook is private, you will not have access to runs however you can still be in a run channel without being a participant. RHS screen is needed to show this state. 

[Figma Designs](https://www.figma.com/file/oBERv3BlbjpcFMKgPAo7E5/%F0%9F%91%A5-Members-%E2%89%A0-Participants?node-id=37%3A125625)

**Comment by trilopin** [comment]
@abhijit-singh is the illustration available as svg file?
