### ISSUE TITLE
When the "Link to an existing channel" is selected, make specifying the channel mandatory

### ISSUE THREAD

**Issue by gbochora** [mattermost/mattermost-plugin-playbooks#1610]
When creating/editing a playbook, if the "Link to an existing channel" is selected, make the linked channel mandatory field.

**Comment by trilopin** [comment]
closed as part of V1 start a run

**Comment by lieut-data** [comment]
@trilopin, to confirm, can we close this issue?

**Comment by gbochora** [comment]
Yes, we can. I remember closing this issue.
