### ISSUE TITLE
can not post update - 403

### ISSUE THREAD

**Issue by trilopin** [mattermost/mattermost-plugin-playbooks#1690]
When I use "Post update" in this channel (note I'm the owner, but did not create this channel nor incident and was added later), after entering the udate and hitting "Post Update" button the modal disappears, but nothing is posted. I see this in the JS console:

_Issue created from a [Mattermost message](https://community.mattermost.com/_redirect/pl/dcj3kebwatrszd61rqixesi9ye) *by @zefhemel*._

**Comment by lieut-data** [comment]
@trilopin, this is effectively fixed now, right?

**Comment by trilopin** [comment]
not until we merge #1751
