### ISSUE TITLE
RHS: Run view

### ISSUE THREAD

**Issue by iomodo** [mattermost/mattermost-plugin-playbooks#1726]
See [Figma file](https://www.figma.com/file/rU4vGGtxk3lBIghH4o0yj6/Checklists?node-id=609%3A244876&t=tdE7PsxEVGqYZ733-0) for reference

![Image](https://user-images.githubusercontent.com/2340127/212020392-47852768-13eb-4f32-b9a6-bf3eece6b7e4.png)

**Comment by lieut-data** [comment]
We're shifting priorities on Playbooks features, and have decided not to ship Channel Checklists at this time. Thanks again, @iomodo!
