### ISSUE TITLE
empty message sent by playbooksbot

### ISSUE THREAD

**Issue by trilopin** [mattermost/mattermost-plugin-playbooks#1740]
Hey Playbooks team, I'm seeing a blank message from the playbooks bot in one of the channels that status updates get posted to. Any idea what might be causing this? Is it a known issue?

_Issue created from a [Mattermost message](https://community.mattermost.com/_redirect/pl/rgz76ku97jffbmkasxggd66n6o) *by @matthewbirtch*._

<img width="854" alt="imageughkjhkjhkjh" src="https://user-images.githubusercontent.com/4096774/212738174-15cced4e-a488-49fb-8c4a-2763566e9e92.png">

**Comment by lieut-data** [comment]
I believe this is fixed by https://github.com/mattermost/mattermost-plugin-playbooks/pull/1697.

**Comment by trilopin** [comment]
🎉 I'd leave this issue open as a reminder to check with Matt after the next deploy.

**Comment by trilopin** [comment]
confirmed that this has been solved
