### ISSUE TITLE
Hidden/Overflowing timeline event duration for some locales

### ISSUE THREAD

**Issue by m-ripper** [mattermost/mattermost-plugin-playbooks#1803]
The timeline event duration is hidden/overflowing for some locales, where the narrow units are not really short like seen in the screenshots beneath. 

> For example, Intl will return "Min." as unit for minutes in German which is considerably longer than "m" in English. 

It could be fixed by adding more space to the left but this will cause the icons to not be aligned anymore with the icons in the overview. 

| English | German |
| ---------- | ----------- |
| ![Screenshot from 2023-02-03 16-53-29](https://user-images.githubusercontent.com/8669935/216647801-e5e39fec-0a23-4d3a-82a1-9709de27bacf.png) | ![Screenshot from 2023-02-03 16-53-20](https://user-images.githubusercontent.com/8669935/216647795-91ae9d1c-373b-4d59-9780-36fee2e6e5ab.png) |

**Comment by lieut-data** [comment]
Closing this to reduce scope in the short-term.
