### ISSUE TITLE
Please don't re-create tags!

### ISSUE THREAD

**Issue by alerque** [mattermost/mattermost-plugin-playbooks#1844]
A tag for v1.36.1 was created at least 6 days ago and was already packaged for some distros. The tag now showing v1.36.1 seems to be a new one as of just now, which means a previous tag was removed.

Please don't do this! It throws off all sorts of stuff downstream. Just create a new tag version like v1.36.2 and move on even if something went wrong with the release process. If you make a tag public, please leave it.

**Comment by lieut-data** [comment]
Hi @alerque, thank you for bringing this to my attention! I didn't realize this repository was being packaged in some way with distros, as the only intended consumer (to date) has been the core Mattermost application itself.

Can you point me at an example distro? We're in the process of merging this plugin's functionality into the core Mattermost product, and I'd love to know if there are more unexpected impacts downstream like this.

**Comment by alerque** [comment]
The [AUR](https://aur.archlinux.org/packages/mattermost-plugin-playbooks) package is the one I bumped into this on because it got reported as being broken (I'd updated it last week). I'm also the packager of the prebuilt [mattermost](https://archlinux.org/packages/community/x86_64/mattermost/) package in official Arch repos. I'm sure there are others.

It looks like you probably did this to change the naming scheme of the attached artifacts. Again that should either have been a new tag or just add both sets of artifacts to the old tag to transition, but it's water under the bridge now, you can't go back. We've already had to deal with the checksum breakage downsteam.

**Comment by lieut-data** [comment]
Understood, and thank you for teaching me about this downstream dependency! Apart from security patches, this repo won't see any new releases, but I'll keep in this in mind going forward for other repos.
