### ISSUE TITLE
German language localization issue

### ISSUE THREAD

**Issue by q-wertz** [mattermost/mattermost-plugin-playbooks#1875]
Since the update to Mattermost 9.1.0 there is an error in the German translation due to:

https://github.com/mattermost/mattermost-plugin-playbooks/commit/cf36b1ed40a8237b680a108d86b30d4489bbb292

The previous translation was correct! (Now it is turkish?!?)

**Comment by q-wertz** [comment]
Looks like it is already fixed in weblate: https://translate.mattermost.com/translate/playbooks/server/de/?checksum=e93048fc365bf749&sort_by=-priority,position

**Comment by jprusch** [comment]
I'm overlooking & translating the German parts. My guess: The Turkish translator picked the wrong language. I wonder if there used to be a way to lock certain languages to specific users...

**Comment by q-wertz** [comment]
I only know they do something like this in Nextcloud which uses Transifex. (I can only edit German translations and had to request first).

Maybe it is also possible that changes to existing translations need a review before they are accepted? But might give quite some overhead.
