### ISSUE TITLE
Deleted Playbook still partly accessible

### ISSUE THREAD

**Issue by jellium** [mattermost/mattermost-plugin-playbooks#707]
#### Summary
Deleting a Playbook does not properly & thoroughly remove it.

#### Steps to reproduce
- Create a Playbook
- Start a Run for this Playbook
- End the Run (maybe not mandatory)
- Delete the Playbook
- Go to the Run list
- Enter the Run just ended
- Access to the Playbook from the link below the Run name (top left hand corner)

#### Expected behavior
- The Playbook should not be accessible, as it has been deleted
- The Playbook should not be editable and saved
- Even though the Playbook is edited and saved, it remains invisible in the Playbook list (as it should be)

#### Observed behavior (that appears unintentional) 
- The Playbook should be deleted
- The Playbook bot prompts 'Playbook not found for id: ...' when starting a Run for this allegedly deleted Playbook

#### Possible fixes
- Remove the Playbook link below the Run title on a specific Run page (see https://mattermost.atlassian.net/browse/MM-37191)
- Actually remove 'deleted' Playbook
- Allow treatment of Runs associated to a deleted Playbook (ability to remove purge those Runs?)
- Allow deletion of Runs

**Comment by lieut-data** [comment]
Thanks for the report, @jellium! Indeed, "deleted" playbooks behave much more like "archived" playbooks at present, and you've correctly identified https://mattermost.atlassian.net/browse/MM-37191 as the fix to suppress trying to encourage running such a playbook. We haven't yet scoped out full semantics for "archived" playbooks, but you're also right that there is a case for making them immutable (unless unarchived).

I'd love to know more about your use cases and how you ran into this issue! Would you be willing to join https://community-daily.mattermost.com/core/channels/developers-playbooks and share any thoughts or feedback?

**Comment by lieut-data** [comment]
@jellium, thanks again for your feedback in-channel. The above ticket has been resolved to at least hide the `Run` prompt when the playbook is archived. We're following up with more changes as part of https://mattermost.atlassian.net/browse/MM-38593 this quarter, which we hope to ship in January.

I'm going to close out this ticket as we track the effort in the linked JIRA ticket above, but feel free to continue to share feedback :)
