### ISSUE TITLE
Playbook not showing in Main Menú

### ISSUE THREAD

**Issue by richilp** [mattermost/mattermost-plugin-playbooks#711]
Hello team,

we're running the last Mattermost version, 5.38.1.
We've activated Playbook plugin.

But it never shows in the Main Menu.
We can create the Playbook with a command, but then when we follow the link to enter the playbook nothing happens.
The link looks like this:
https://xxxxxxxxxxxxxxxx.com/chat/com.mattermost.plugin-incident-management/playbooks/dhkrp53c6bgjuxsmjyfyk4hryw

Not sure if we're doing smth wrong.

Any ideas?

Thank you !!
Richi

**Comment by agarciamontoro** [comment]
Thank you for the report, @richilp! A couple of questions:

- What version of Playbooks are you running? You can check in the System Console, in the Plugin Management entry under the Plugins section.
- I see that you are running Mattermost under the subpath `/chat`. Is that correct?

**Comment by richilp** [comment]
Thanks Alejandro,

We're running Playbooks version --> 1.16.1

And yes, we use the subpath /chat

Thank you ;)

**Comment by agarciamontoro** [comment]
We're investigating whether one of our latest features is conflicting with the subpath deployment, we'll keep you updated! :)

**Comment by agarciamontoro** [comment]
@richilp, we've definiteely identified a problem with subpath deployments, but the missing menu entry is still puzzling me. Just to double check: is the highlighted entry in the screenshot what you don't see?
![image](https://user-images.githubusercontent.com/3924815/130654354-dd55cf19-3089-4836-93ea-1a8cd343c94b.png)

**Comment by richilp** [comment]
Thanks @agarciamontoro, please check my menu:

![image](https://user-images.githubusercontent.com/16322989/130756101-83629b1e-7037-45f8-b554-75e5acfb05c9.png)

Could it be a language issue?

**Comment by agarciamontoro** [comment]
There should not be any problem with the language, the Playbooks entry would just be untranslated.

A couple more questions:
1. Is your server licensed? If so, which license?
2. Is Playbooks enabled for that team? You can check in the System Console > Plugins > Playbooks, in the `Enabled Teams` setting.

By the way, the problem with the subpath is being tracked with this ticket, in case you want to keep yourself updated: https://mattermost.atlassian.net/browse/MM-38129

**Comment by richilp** [comment]
**Is your server licensed? If so, which license?**
Do you mean Mattermost?. We're using the Team Version.
The server is Centos 7

**Is Playbooks enabled for that team? You can check in the System Console > Plugins > Playbooks, in the Enabled Teams setting.**
Yes, it is.
![image](https://user-images.githubusercontent.com/16322989/130764839-ffbd90f1-39fc-4a72-b1b6-4cf38f15b840.png)

Thanks @agarciamontoro

**Comment by agarciamontoro** [comment]
> **Is your server licensed? If so, which license?**
> Do you mean Mattermost?. We're using the Team Version.
> The server is Centos 7

Yes, I meant that, thanks!

> **Is Playbooks enabled for that team? You can check in the System Console > Plugins > Playbooks, in the Enabled Teams setting.**
> Yes, it is.

I mean this setting here, which can be used to enable/disable the plugin only on specific teams:
![image](https://user-images.githubusercontent.com/3924815/130765587-3520ccd9-abb2-4644-8e99-885aa319176e.png)

**Comment by agarciamontoro** [comment]
Cool, thanks for the info, I wanted to discard the obvious causes first :)

**Comment by richilp** [comment]
Thanks @itao, yes we can see it now after v.6

Thanks you so much for the following up ;)
