### ISSUE TITLE
Subpath Deployments are not working

### ISSUE THREAD

**Issue by oguera** [mattermost/mattermost-plugin-playbooks#713]
As already mentioned in #711 the subpath deployment is not working correctly. For some parts of the plugin the requests are made against `domain.tld/plguins` instead of `domain.tld/subpath/plugins`.

I'll follow up with some more detailed information; i just wanted to extract this issue from #711 because there are two issues in there.

**Comment by lieut-data** [comment]
@oguera, apologies for the delay in linking back to this issue, but this have been resolved with our v6.0 release last month. Let us know if you have any other issues!
