### ISSUE TITLE
Pre-assign tasks

### ISSUE THREAD

**Issue by luc-ass** [mattermost/mattermost-plugin-playbooks#873]
Hey there, 

I just started playing around with Playbooks in our Mattermost instance. Looks like this could make onboarding for new coworkers simpler and more structured. As we have certain tasks that are performed, could I pre-assign specific tasks to specific people?

Thanks a lot! Lucas

**Comment by itao** [comment]
Hey Lucas!

We're brainstorming this feature actually! Could you clarify if your use case is to pre-assign to the same specific individual every time the playbook runs (eg. Angela or Steve), or to a pre-assign role so whoever fills that roles becomes the assignee (eg. The New Hire or Team Lead)

**Comment by luc-ass** [comment]
Both cases would actually be extremely helpful. In our case it would be something like:
1. Give out keys @angela
2. Create Mattermost Account @lucas

**Comment by itao** [comment]
Ah gotcha. And in the case where you have multiple people on a task, is there one clear owner? For example, is the intention to @ mention people or is it to assign ownership? (ie. either person can check off? require both to check off?)

**Comment by luc-ass** [comment]
Either can check it off. At least for our use case.

**Comment by lieut-data** [comment]
Just to share more on this front: we're hoping to tackle exactly this feature in Q1 2022. Stay tuned!

**Comment by Kazintsev** [comment]
We are planning to migrate some of our workflows to Mattermost. This feature would be extremely helpful to us. Looking forward to updates!

**Comment by luc-ass** [comment]
Yeah, curious. Any updates on this?

**Comment by luc-ass** [comment]
Sounds like this is just what I wanted. Any way to test this out?

**Comment by lieut-data** [comment]
We're hoping to merge it next week, after which there will be a build available here, and also include it in v7.7 (January) unless other issues are found.

**Comment by lieut-data** [comment]
@luc-ass, thanks to @m-ripper's efforts, this has shipped:

<img width="1265" alt="CleanShot 2023-01-25 at 13 48 44@2x" src="https://user-images.githubusercontent.com/1023171/214642487-ab9c5789-d66b-4723-812a-5e0b094e10ec.png">

Users with pre-assigned tasks are also invited automatically:

<img width="1003" alt="CleanShot 2023-01-25 at 13 48 50@2x" src="https://user-images.githubusercontent.com/1023171/214642527-4b3262a5-3776-4768-873c-01b0e75f5f2f.png">

Let us know if you have more ideas :)

**Comment by luc-ass** [comment]
Thanks, we have already tested one run with the new task assignment. It works and looks great.

We noticed, that tasks can only be assigned to one person at a time. Could this be changed to allow for more assignees? 

Our use-case would be, that some tasks are performed by two people and there is also a backup for if someone is sick.

**Comment by lieut-data** [comment]
Got it, @luc-ass! We've had another request for this too -- https://github.com/mattermost/mattermost-plugin-playbooks/issues/1247. cc @itao
