### ISSUE TITLE
Schedule a playbook to run periodically

### ISSUE THREAD

**Issue by lubritto** [mattermost/mattermost-plugin-playbooks#889]
Hello, Is there a way to schedule a playbook to run periodically? For example, schedule it to run every week on Thursday morning? If not, I would like to leave this suggestion.

**Comment by itao** [comment]
Hey! We're currently exploring different triggers that automatically run a playbook and date time is one of the candidates. 

Could you tell us more about your use case?

**Comment by lieut-data** [comment]
Thanks for the inquiry, @lubritto! I'm going to close out this ticket for now, but happy to continue the conversation either here on on https://community-daily.mattermost.com/core/channels/developers-playbooks.
