### ISSUE TITLE
Plural forms at Weblate

### ISSUE THREAD

**Issue by milotype** [mattermost/mattermost-plugin-playbooks#957]
Please specify, how plurar forms should be translated at Weblate … which part of the strings should be translated and how. Please give an example for Croatian (which uses plural forms "one", "few", "other").

I'm not a  programmer, so  I'm insecure how to go about it …

For instance:
- `{numActiveRuns, plural, =0 {no active runs} =1 {# active run} other {# active runs}}` (key 1MQ3XZ)
- `{numParticipants, plural, =0 {no active participants} =1 {# active participant} other {# active participants}}` (key Q7aZO4)
- `{num_runs, plural, =0 {Not run yet} one {# run} other {# total runs}}` (key YDuW/T)
- `{numTotalRuns, plural, =0 {no runs started} =1 {# run started} other {# runs started}}` (key sQu1rA)
- `{num_checklists, plural, =0 {no checklists} one {# checklist} other {# checklists}}` (key soePYH)

I have the same problem with **Focalboard webapp** at Weblate for:
- `{count, plural, one {# Board} few {# Boards} other {# Boards}}` (key General.BoardCount )

**Comment by calebroseland** [comment]
Hi @milotype, 

These are ICU Messages, and a short plural example can be found here: https://devpal.co/icu-message-editor/

If you search in the repo for those exact strings, you'll find where they're used, and potentially show examples of how they've already been translated (in the `i18n/**.json` files).

e.g. https://github.com/mattermost/mattermost-plugin-playbooks/search?q=%7BnumActiveRuns%2C+plural%2C+%3D0+%7Bno+active+runs%7D+%3D1+%7B%23+active+run%7D+other+%7B%23+active+runs%7D%7D

While not always adhere'd to, it's usually better to use the worded categories (`zero`, `one`) over the explicit number (`=0`, `=1`, etc.)

Some additional resources/links:
https://cldr.unicode.org/index/cldr-spec/plural-rules (recommended)
https://formatjs.io/docs/core-concepts/icu-syntax/#plural-format (the tool we use in the webapp to process these strings)
https://unicode-org.github.io/cldr-staging/charts/latest/supplemental/language_plural_rules.html#hr (may or may not help)

Also, feel free to join us in https://community.mattermost.com/core/channels/localization! This channel is probably the quickest avenue if you have any questions/thoughts/comments.

**Comment by milotype** [comment]
Thank you for the link "https://devpal.co/icu-message-editor/". It has helped me a lot!

Milo

**Comment by milotype** [comment]
Issue resolved ...
